
name: Benchmark with Benchpress
description: Easy Benchmarking with PowerShell
inputs: 
  BenchmarkPath: 
    required: false
    description: |
      The path to the benchmark file.  
      If not provided, any benchmark files in your repository will be used
  ModulePath: 
    required: false
    description: The path to the module.
  
runs: 
  using: composite
  steps: 
    - name: Benchpress
      shell: pwsh
      env: 
        BenchmarkPath: ${{inputs.BenchmarkPath}}
        ModulePath: ${{inputs.ModulePath}}
      run: |
        $Parameters = @{}
        $Parameters.BenchmarkPath = ${env:BenchmarkPath}
        $Parameters.ModulePath = ${env:ModulePath}
        foreach ($k in @($parameters.Keys)) {
            if ([String]::IsNullOrEmpty($parameters[$k])) {
                $parameters.Remove($k)
            }
        }
        Write-Host "::debug:: Benchpress $(@(foreach ($p in $Parameters.GetEnumerator()) {'-' + $p.Key + ' ' + $p.Value}) -join ' ')"
        & {<#
        .Synopsis
            Benchpress Action
        .Description
            Runs Benchmarks on your code.
        #>
        param(
        # The path to the benchmark file.  
        # If not provided, any benchmark files in your repository will be used
        [string]
        $BenchmarkPath,
        # The path to the module.
        [string]
        $ModulePath
        )
        
        if (-not $BenchmarkPath) {
            $BenchmarkPath = Get-ChildItem -Recurse | Where-Object Name -Like '*.benchmark.*' | Split-Path | Select-Object -Unique
        }
        
        if ($env:Action_Path) {
            $benchPressPath = Join-Path $env:Action_Path $benchPressPath
            if (Test-path $benchPressPath) {
                Import-Module $benchPressPath -Force -PassThru | Out-String
            } else {
                throw "Benchmark not found"
            }
        }
        
        if (-not $ModulePath) {
            Get-ChildItem -ErrorAction SilentlyContinue -Path $BenchmarkPath -Filter *.psd1
        } elseif (-not (Test-Path $ModulePath) -and $env:GitHub_WorkSpace) {
            $ModulePath = Join-Path (Join-Path $env:GitHub_WorkSpace "RepositoryToBenchmark") $ModulePath
        }
        
        if ($modulePath -and (Test-Path $ModulePath -ErrorAction SilentlyContinue )) {
            Import-Module $ModulePath -Force -PassThru | Out-String
        }
        
        $benchpressModule = Get-Module Benchpress
        if (-not $benchpressModule) { throw "Benchpress not loaded" }
        
        $startTime = [DateTime]::Now
        $benchMarkOutput = Get-ChildItem -Path $BenchmarkPath -ErrorAction SilentlyContinue |
            Where-Object Name -Like '*.benchmark.*' |
            Checkpoint-Benchmark
        
        
        
        $endTime = [DateTime]::Now
        "::set-output name=TotalDuration::$(($endTime - $startTime).TotalSeconds)" | Out-Host
        "::set-output name=OutputClixml::$([Management.Automation.PSSerializer]::Serialize($BenchMarkOutput, 5))"
        "::set-output name=OutputJSON::$(ConvertTo-Json $BenchMarkOutput -Depth 5 -Compress)"
        
        $benchMarkOutput | Export-Clixml "BenchmarkOutput.clixml"
        $benchMarkOutput | ConvertTo-Json -Depth 5 | Export-Clixml "benchmarkOutput.json" 
        
        
        } @Parameters

